%Function for MATLAB Problem 1, Assignment 3
%Editor: Gerardo E. Rodriguez, ger150030
%Adapted from gael.m
%Function that performs Gaussian Elimination with Partial Pivoting

function [A,P] = gaelpp(A)

%Gaussian elimination with partial pivoting
%inputs: 
%nXn matrix A
%outputs: 
%nXn matrix P of permutation matrix 
%nXn mixed triangular matrix A
%%Bottom triangle of A has multipliers
%%Upper triangle is triangle matrix generated by GEPP

%get n
[n,n] = size(A);

%Initialize P
P = eye(n);

%Gaussian elimination
for j = 1:n-1 %j is pivot row
    
    %Max value of A(j:n,j) in maxI+j-1(row)
    %First part is rows, second is columns
    [maxNum,maxI] = max(A(j:n,j));
    maxI = maxI+j-1;

    if maxNum == 0 %avoid div. by 0
            break
    end
    
    %Exchange rows in A
    temp = A(j,:);
    A(j,:) = A(maxI,:);
    A(maxI,:) = temp;
    
    %Record exchange in P
    temp = P(j,:);
    P(j,:) = P(maxI,:);
    P(maxI,:) = temp;
    
    for i = j+1:n %elim. col. j from row i = j+1 to i = n
        
        A(i,j) = A(i,j)/A(j,j); %multiplier to elim. A(i,j), store in matrix A
        
        
        for k = j+1:n % add mult of row j to row i
            
            A(i,k) = A(i,k) - A(i,j)*A(j,k); 
            
        end
                
    end
    
end